"""
Re-derive the aggregates behind Table 5 (row 4), Table 7 and Table 10 (column 2)
of the paper from the per-sample evaluation and replay logs.

THIS IS NOT THE ORIGINAL SCRIPT. The script that first computed these values
was not preserved. This one was written for release v1.0.1 (2026-09-11) to
re-derive the published values from the preserved logs; it reproduces them
exactly (Table 5: 89,877 calls; Table 7: 39,177 calls; Table 10: 122,841 /
462,839 / 65 calls).

Inputs (the logs are not included in this repository; they are regenerated by
stage 2 of the pipeline, see README):
  --eval-dir    directory holding <sha256>_eval.json   (log_evaluator.py --json)
  --replay-dir  directory holding <sha256>_result.json (WinAPIReplay.exe --result-json)
Outputs (written to --out-dir):
  table5_bias_by_api.csv              api,success_calls,share_of_l1_total_pct
  table7_substitute_by_group.csv      group,calls,share_of_l1_successes_pct
  table10_intercepted_by_category.csv category,intercepted_and_redirected_calls

Definitions and their sources (the authors' revision record revision_plan.md,
which is not part of this repository):
  * Layer-1 calls: details[] entries whose category is not "unknown" and whose
    replay_outcome is success, failed or approx (revision_plan.md L290-296).
    L1 total = 1,352,778; L1 successes = 1,001,634.
  * Table 5, row 4: calls counted as success for which the executor returns
    the expected status without inspecting the outcome of the underlying
    operation. API set: NtWaitForSingleObject; NtOpenProcess,
    NtOpenProcessToken, NtOpenThread; NtFreeVirtualMemory
    (revision_plan.md L3712-3725; 89,877 / 1,352,778 at L3807).
  * Table 7, groups 1-7: success calls of the APIs listed per group in
    revision_plan.md L6972-6984 (GROUPS below).
  * Table 7, group 8: NtCreateFile / NtOpenFile / NtDeleteFile calls with
    outcome success whose path transform was rewritten beneath
    C:\\Sandbox\\relative\\, i.e. the recorded path carries no drive letter
    (device paths and named pipes) and the executor short-circuits the open
    (revision_plan.md L2530-2540 and L6957). Counted per call, not per
    transform.
  * Table 10, column 2: per-category success + failed + approx over the
    details[] entries, for file, registry and network_winsock
    (revision_plan.md L2859).

Standard library only.
"""
import argparse
import csv
import json
from collections import Counter
from pathlib import Path

L1_OUTCOMES = ('success', 'failed', 'approx')

TABLE5_APIS = [
    'NtWaitForSingleObject',
    'NtOpenProcess',
    'NtOpenProcessToken',
    'NtOpenThread',
    'NtFreeVirtualMemory',
]

# Group labels are those of Table 7 of the paper.
GROUPS = [
    ('Process and shell creation suppressed',
     ['CreateProcessW', 'CreateProcessA', 'NtCreateUserProcess', 'WinExec', 'ShellExecuteExW']),
    ('Thread created with a placeholder start routine',
     ['CreateThread', 'NtCreateThreadEx']),
    ('Cross-process memory access not performed',
     ['NtReadVirtualMemory', 'NtWriteVirtualMemory', 'WriteProcessMemory', 'ReadProcessMemory']),
    ('Hook installation answered with a sentinel',
     ['SetWindowsHookExA', 'SetWindowsHookExW']),
    ('Service start reported without being attempted',
     ['StartServiceW']),
    ('Thread-attribute update not performed',
     ['UpdateProcThreadAttribute']),
    ('Data-carrying calls issued with substitute buffers',
     ['NtWriteFile', 'CryptHashData']),
]
GROUP8_LABEL = 'Opens of device paths and named pipes short-circuited'
GROUP8_APIS = ('NtCreateFile', 'NtOpenFile', 'NtDeleteFile')
RELATIVE_ROOT = 'c:\\sandbox\\relative\\'

TABLE10_CATEGORIES = ['file', 'registry', 'network_winsock']


def scan_eval(eval_dir):
    api_success = Counter()
    cat_l1 = Counter()
    l1_total = l1_success = 0
    files = sorted(eval_dir.glob('*_eval.json'))
    for p in files:
        with open(p, encoding='utf-8') as f:
            doc = json.load(f)
        for d in doc.get('details', []):
            outcome = d.get('replay_outcome')
            category = d.get('category')
            if outcome == 'success':
                api_success[d.get('api_name')] += 1
            if category != 'unknown' and outcome in L1_OUTCOMES:
                l1_total += 1
                cat_l1[category] += 1
                if outcome == 'success':
                    l1_success += 1
    return len(files), api_success, cat_l1, l1_total, l1_success


def scan_replay(replay_dir):
    count = 0
    files = sorted(replay_dir.glob('*_result.json'))
    for p in files:
        with open(p, encoding='utf-8') as f:
            doc = json.load(f)
        for r in doc.get('results', []):
            if r.get('api_name') not in GROUP8_APIS or r.get('outcome') != 'success':
                continue
            if any(str(t.get('rewritten', '')).lower().startswith(RELATIVE_ROOT)
                   for t in (r.get('transforms') or [])):
                count += 1
    return len(files), count


def pct(n, d):
    return f'{100.0 * n / d:.2f}'


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--eval-dir', required=True, type=Path)
    ap.add_argument('--replay-dir', required=True, type=Path)
    ap.add_argument('--out-dir', required=True, type=Path)
    a = ap.parse_args()
    a.out_dir.mkdir(parents=True, exist_ok=True)

    n_eval, api_success, cat_l1, l1_total, l1_success = scan_eval(a.eval_dir)
    n_replay, group8 = scan_replay(a.replay_dir)
    print(f'eval files: {n_eval}  replay files: {n_replay}')
    print(f'L1 total: {l1_total}  L1 successes: {l1_success}')

    with open(a.out_dir / 'table5_bias_by_api.csv', 'w', newline='', encoding='utf-8') as f:
        w = csv.writer(f, lineterminator='\n')
        w.writerow(['api', 'success_calls', 'share_of_l1_total_pct'])
        total = 0
        for api in TABLE5_APIS:
            n = api_success[api]
            total += n
            w.writerow([api, n, pct(n, l1_total)])
        w.writerow(['TOTAL', total, pct(total, l1_total)])
    print(f'Table 5 row 4: {total}')

    with open(a.out_dir / 'table7_substitute_by_group.csv', 'w', newline='', encoding='utf-8') as f:
        w = csv.writer(f, lineterminator='\n')
        w.writerow(['group', 'calls', 'share_of_l1_successes_pct'])
        total = 0
        for label, apis in GROUPS:
            n = sum(api_success[x] for x in apis)
            total += n
            w.writerow([label, n, pct(n, l1_success)])
        total += group8
        w.writerow([GROUP8_LABEL, group8, pct(group8, l1_success)])
        w.writerow(['TOTAL', total, pct(total, l1_success)])
    print(f'Table 7 total: {total}')

    with open(a.out_dir / 'table10_intercepted_by_category.csv', 'w', newline='', encoding='utf-8') as f:
        w = csv.writer(f, lineterminator='\n')
        w.writerow(['category', 'intercepted_and_redirected_calls'])
        for c in TABLE10_CATEGORIES:
            w.writerow([c, cat_l1[c]])
    print('Table 10 column 2: ' + ' / '.join(f'{c} {cat_l1[c]}' for c in TABLE10_CATEGORIES))


if __name__ == '__main__':
    main()
