"""
Supplementary figure generator for experiments 1-4.
Reads from canonical CSV outputs and regenerates PNG figures.

Excel tables are generated by generate_tables_and_draft.py (not this script).
Figures are also generated by generate_reports.py (Exp1) and generate_exp3.py
(Exp3 scatter); this script reads from the CSV outputs for standalone regeneration.

Canonical CSV column names:
  exp1_summary.csv  : family, n_samples, total_events,
                      l1_total, l1_success,
                      l1_brr_agg, l1_brr_mean, l1_brr_sd, l1_brr_median,
                      active_asr_mean, ASR_pct, BMR_pct,
                      skipped_events, failed_events, approx_events  (row label 'OVERALL', not 'ALL')
  exp1_detail.csv   : family, sha256, ..., l1_total, l1_success, l1_brr,
                      file_total, file_success, file_rate,
                      registry_total, registry_success, registry_rate,
                      network_winsock_total, network_winsock_success, network_winsock_rate,
                      process_total, process_success, process_rate,
                      dll_total, dll_success, dll_rate
  exp3_timing.csv   : family, stem, total_events, elapsed_ms, dry_ms, overhead_pct
"""
import csv
from pathlib import Path

BASE     = Path('C:/Projects/Experiments')
RESULTS  = BASE / 'results'
REPORTS  = BASE / 'reports'
REPORTS.mkdir(exist_ok=True)

FAMILIES   = ['agenttesla', 'amadey', 'berbew', 'dacic', 'redline']
CATEGORIES = ['file', 'registry', 'network_winsock', 'process', 'dll']


def read_csv(path):
    with open(path, newline='', encoding='utf-8') as f:
        return list(csv.DictReader(f))


# -----------------------------------------------------------------------
# fig_exp1_family.png
# -----------------------------------------------------------------------
def fig_exp1_family():
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    import numpy as np

    rows = [r for r in read_csv(RESULTS / 'exp1_summary.csv')
            if r['family'] != 'OVERALL']
    FAM_DISP = {'agenttesla': 'AgentTesla'}
    labels  = [FAM_DISP.get(r['family'], r['family'].capitalize()) for r in rows]
    l1_brr  = [float(r.get('l1_brr_mean', 0) or 0) for r in rows]
    l1_sd   = [float(r.get('l1_brr_sd',   0) or 0) for r in rows]
    bmatch  = [float(r.get('BMR_pct',     0) or 0) for r in rows]

    x = np.arange(len(labels))
    w = 0.35
    fig, ax = plt.subplots(figsize=(8, 5))
    b1 = ax.bar(x - w / 2, l1_brr, w, label='L1 BRR (mean ±1 SD)',
                color='#2196F3', alpha=0.85,
                yerr=l1_sd, capsize=4, error_kw={'elinewidth': 1.2})
    b2 = ax.bar(x + w / 2, bmatch, w, label='BMR (supplementary)',
                color='#BBBBBB', alpha=0.60)
    ax.set_xlabel('Malware Family')
    ax.set_ylabel('Rate (%)')
    ax.set_title('Experiment 1: Per-Family L1 BRR (Primary) and BMR (Supplementary)')
    ax.set_xticks(x)
    ax.set_xticklabels(labels)
    ax.set_ylim(0, 100)
    ax.legend()
    ax.grid(axis='y', alpha=0.3)
    for rect, val in zip(b1, l1_brr):
        ax.text(rect.get_x() + rect.get_width() / 2, rect.get_height() + 1,
                f'{val:.1f}%', ha='center', va='bottom', fontsize=8)
    for rect, val in zip(b2, bmatch):
        ax.text(rect.get_x() + rect.get_width() / 2, rect.get_height() + 1,
                f'{val:.1f}%', ha='center', va='bottom', fontsize=8)
    fig.tight_layout()
    out = REPORTS / 'fig_exp1_family.png'
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f'Saved: {out}')


# -----------------------------------------------------------------------
# fig_exp1_category.png
# -----------------------------------------------------------------------
def fig_exp1_category():
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt

    detail = read_csv(RESULTS / 'exp1_detail.csv')
    totals = {c: sum(int(r.get(f'{c}_total',   0) or 0) for r in detail)
              for c in CATEGORIES}
    succs  = {c: sum(int(r.get(f'{c}_success', 0) or 0) for r in detail)
              for c in CATEGORIES}
    rates  = [succs[c] / totals[c] * 100 if totals[c] else 0 for c in CATEGORIES]
    labels = ['File', 'Registry', 'Network\n(Winsock)', 'Process', 'DLL']
    colors = ['#4CAF50', '#2196F3', '#FF9800', '#9C27B0', '#F44336']
    fig, ax = plt.subplots(figsize=(8, 5))
    bars = ax.bar(labels, rates, color=colors, alpha=0.85)
    ax.set_xlabel('API Category')
    ax.set_ylabel('Success Rate (%)')
    ax.set_title('Experiment 1: Per-Category Replay Success Rate')
    ax.set_ylim(0, 100)
    ax.grid(axis='y', alpha=0.3)
    for bar, rate, cat in zip(bars, rates, CATEGORIES):
        t = totals[cat]
        ax.text(bar.get_x() + bar.get_width() / 2, bar.get_height() + 1,
                f'{rate:.1f}%\n({t:,})', ha='center', va='bottom', fontsize=7)
    fig.tight_layout()
    out = REPORTS / 'fig_exp1_category.png'
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f'Saved: {out}')


# -----------------------------------------------------------------------
# fig_exp3_scatter.png  (also generated by generate_exp3.py)
# -----------------------------------------------------------------------
def fig_exp3_scatter():
    import matplotlib
    matplotlib.use('Agg')
    import matplotlib.pyplot as plt
    import numpy as np

    timing = read_csv(RESULTS / 'exp3_timing.csv')
    fam_colors = {'redline': '#F44336', 'agenttesla': '#2196F3',
                  'amadey': '#4CAF50', 'berbew': '#FF9800', 'dacic': '#9C27B0'}
    fig, ax = plt.subplots(figsize=(8, 6))
    all_xs, all_ys = [], []
    for fam in FAMILIES:
        pts = [(int(r.get('total_events', 0) or 0), float(r.get('elapsed_ms', 0) or 0) / 1000)
               for r in timing
               if r.get('family') == fam]
        if pts:
            xs, ys = zip(*pts)
            label = 'AgentTesla' if fam == 'agenttesla' else fam.capitalize()
            ax.scatter(xs, ys, c=fam_colors[fam], label=label, alpha=0.6, s=30)
            all_xs.extend(xs)
            all_ys.extend(ys)
    if len(all_xs) >= 2:
        z = np.polyfit(all_xs, all_ys, 1)
        xfit = np.linspace(0, max(all_xs), 100)
        ax.plot(xfit, np.poly1d(z)(xfit), 'k--', alpha=0.4, lw=1, label='Linear fit')
    ax.set_xlabel('Event Count')
    ax.set_ylabel('Elapsed Time (s)')
    ax.set_title('Experiment 3: Execution Time vs. API Event Count')
    if ax.get_legend_handles_labels()[1]:
        ax.legend(fontsize=8)
    ax.grid(alpha=0.3)
    fig.tight_layout()
    out = REPORTS / 'fig_exp3_scatter.png'
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f'Saved: {out}')


# -----------------------------------------------------------------------
def print_key_stats():
    summary = read_csv(RESULTS / 'exp1_summary.csv')
    overall = next((r for r in summary if r['family'] == 'OVERALL'), None)
    if not overall:
        print('[WARN] No OVERALL row found in exp1_summary.csv')
        return
    print(f'\n=== KEY RESULTS ===')
    print(f'n={overall.get("n_samples","?")}  '
          f'L1_Coverage={overall.get("l1_coverage_rate","?")}%  '
          f'L1_BRR={overall.get("l1_brr_agg","?")}%  '
          f'95%CI=[{overall.get("l1_brr_ci_low","?")}%,{overall.get("l1_brr_ci_high","?")}%]  '
          f'ASR={overall.get("ASR_pct","?")}%  BMR(suppl.)={overall.get("BMR_pct","?")}%')

    detail = read_csv(RESULTS / 'exp1_detail.csv')
    print('Category success rates:')
    for cat in CATEGORIES:
        t = sum(int(r.get(f'{cat}_total',   0) or 0) for r in detail)
        s = sum(int(r.get(f'{cat}_success', 0) or 0) for r in detail)
        rate = s / t * 100 if t else 0
        print(f'  {cat:25s}: {rate:5.1f}%  ({s:,}/{t:,})')

    timing = read_csv(RESULTS / 'exp3_timing.csv')
    ms_vals = [int(float(r['elapsed_ms'])) for r in timing if r.get('elapsed_ms')]
    if ms_vals:
        print(f'\nTiming: mean={sum(ms_vals) // len(ms_vals)} ms  '
              f'max={max(ms_vals)} ms  n={len(ms_vals)}')


# -----------------------------------------------------------------------
if __name__ == '__main__':
    print('Generating figures...')
    fig_exp1_family()
    fig_exp1_category()
    fig_exp3_scatter()
    print_key_stats()
    print('\nDone.  For Excel tables run: python generate_tables_and_draft.py')
